### ISSUE TITLE
Semicolon character literal shouldn't be treated as starting a comment

### ISSUE THREAD

**Issue by kommen** [nextjournal/codemirror.next-clojure#7]
```clojure
(println "not a comment" \;)
```
from https://nextjournal.github.io/codemirror.next-clojure/
<img width="255" alt="Screenshot 2020-11-03 at 22 33 35" src="https://user-images.githubusercontent.com/258/98042914-ade42c80-1e24-11eb-8103-dbc1372a6aca.png">

**Comment by mk** [comment]
Fixed with 9c3daa064ea5471855fee4220e3a3d0ab1926725 which brings in https://github.com/lezer-parser/clojure/pull/11
